KIT ;
  IDL VERSION 1.2.8 ;
  TITLE 'SPIF' ;
  AUTHOR 'Domingo Morales-Palma' ;
  CREATION DATE 15/4/2021 ;
  PROJECT NAME 'MfM Use Case: SPIF' ;

  MODEL 'SPIF'
    {LWI
    F 0 -13 0 0 0 400
      0 0 0 204 3 2 1 34
      100 'Arial'
    F 1 -24 0 0 0 400
      0 0 0 204 3 2 1 34
      190 'Arial'
    F 2 -11 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Courier New'
    F 3 -8 0 0 0 400
      0 0 0 204 3 2 1 34
      60 'Dialog'
    F 4 -12 0 0 0 400
      0 0 0 204 3 2 1 34
      90 'Dialog'
    F 5 -10 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Dialog'
    D 0 0 0 0 0 1 0 0 2
    G 0 1
    T 'WORKING'
    R 77
    M 0 }
   ;
    AUTHOR 'Domingo Morales-Palma' ;
    PROJECT NAME 'MfM Use Case: SPIF' ;
    DIAGRAM GRAPHIC A-0 ;
      CREATION DATE 22/2/2018 ;
      REVISION DATE 22/2/2018 ;
      TITLE 'SPIF' ;
      STATUS WORKING ;

      BOX 0 ;
        NAME '{LWI I 4 255 255 255}Produce Part by SPIF' ;
        BOX COORDINATES (0.156,0.742) (0.717,0.306) ;
        DETAIL REFERENCE N A0 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER ;
        PATH (0.316,0.968)(0.316,0.742) ;
        LABEL '{LWI I 0 255 255 }NC Machine' ;
        LABEL COORDINATES (0.293,0.929) ;
        SINK BOX 0M1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER ;
        PATH (0.223,0.031)(0.223,0.306) ;
        LABEL '{LWI I 0 255 255 }Final Part<CR>Model' ;
        LABEL COORDINATES (0.2,0.183) ;
        SINK BOX 0C1 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BORDER ;
        PATH (0.34,0.031)(0.34,0.306) ;
        LABEL '{LWI I 0 255 255 }SPIF Knowledge' ;
        LABEL COORDINATES (0.312,0.183) ;
        SINK BOX 0C2 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BORDER ;
        PATH (0.463,0.031)(0.463,0.306) ;
        LABEL '{LWI I 0 255 255 }Quality and Inspection Rules' ;
        LABEL COORDINATES (0.415,0.165) ;
        SINK BOX 0C3 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BORDER ;
        PATH (0.605,0.031)(0.605,0.306) ;
        LABEL '{LWI I 0 255 255 }Customer and Company Standars' ;
        LABEL COORDINATES (0.547,0.22) ;
        SINK BOX 0C4 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BOX 0O1 ;
        PATH (0.717,0.393)(0.977,0.393) ;
        LABEL '{LWI I 0 255 255 }SPIF Setup Definition' ;
        LABEL COORDINATES (0.805,0.374) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BOX 0O2 ;
        PATH (0.717,0.655)(0.977,0.655) ;
        LABEL '{LWI I 0 255 255 }Manufactured Part' ;
        LABEL COORDINATES (0.786,0.638) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BORDER ;
        PATH (0.205,0.968)(0.205,0.742) ;
        LABEL '{LWI I 0 255 255 }CAD-CAM<CR>System' ;
        LABEL COORDINATES (0.19,0.901) ;
        SINK BOX 0M2 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BORDER ;
        PATH (0.459,0.968)(0.459,0.742) ;
        LABEL '{LWI I 0 255 255 }Forming Tool' ;
        LABEL COORDINATES (0.43,0.92) ;
        SINK BOX 0M3 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BORDER ;
        PATH (0.526,0.968)(0.526,0.742) ;
        LABEL '{LWI I 0 255 255 }Clamping<CR>Tools' ;
        LABEL COORDINATES (0.508,0.829) ;
        SINK BOX 0M4 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BOX 0O3 ;
        PATH (0.717,0.48)(0.977,0.48) ;
        LABEL '{LWI I 0 255 255 }NC Program' ;
        LABEL COORDINATES (0.82,0.456) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BOX 0O4 ;
        PATH (0.717,0.568)(0.977,0.568) ;
        LABEL '{LWI I 0 255 255 }Technical Report' ;
        LABEL COORDINATES (0.795,0.547) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BORDER ;
        PATH (0.268,0.968)(0.268,0.742) ;
        LABEL '{LWI I 0 255 255 }FEA<CR>System' ;
        LABEL COORDINATES (0.244,0.847) ;
        SINK BOX 0M5 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BORDER ;
        PATH (0.393,0.968)(0.393,0.742) ;
        LABEL '{LWI I 0 255 255 }3D<CR>Scanner<CR>System' ;
        LABEL COORDINATES (0.371,0.856) ;
        SINK BOX 0M6 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BORDER ;
        PATH (0.596,0.968)(0.596,0.742) ;
        LABEL '{LWI I 0 255 255 }Measurement<CR>Tools' ;
        LABEL COORDINATES (0.571,0.892) ;
        SINK BOX 0M7 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BORDER ;
        PATH (0.668,0.968)(0.668,0.742) ;
        LABEL '{LWI I 0 255 255 }NC Code<CR>Converter' ;
        LABEL COORDINATES (0.649,0.82) ;
        SINK BOX 0M8 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A0 ;
      CREATION DATE 22/2/2018 ;
      REVISION DATE 22/2/2018 ;
      TITLE 'Produce Part by SPIF' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Define NC Program' ;
        BOX COORDINATES (0.103,0.397) (0.293,0.133) ;
        DETAIL REFERENCE N A1 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Finite Element Analysis' ;
        BOX COORDINATES (0.356,0.56) (0.586,0.433) ;
        DETAIL REFERENCE N A2 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Manufacture and Inspect Part' ;
        BOX COORDINATES (0.566,0.833) (0.844,0.679) ;
        DETAIL REFERENCE N A3 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER M1 (0.597,0.968) ;
        PATH (0.597,0.968)(0.597,0.833) ;
        LABEL '{LWI I 0 255 255 }NC Machine' ;
        LABEL COORDINATES (0.576,0.938) ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER C1 (0.198,0.031) ;
        PATH (0.198,0.031)(0.198,0.091) ;
        LABEL 'Final Part Model' ;
        SINK BRANCH 12 11 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BORDER C3 (0.789,0.031) ;
        PATH (0.789,0.031)(0.789,0.679) ;
        LABEL '{LWI I 0 255 255 }Quality and Inspection<CR>Rules' ;
        LABEL COORDINATES (0.751,0.056) ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BOX 1O1 ;
        PATH (0.293,0.168)(0.513,0.168) ;
        LABEL 'SPIF Setup Definition' ;
        SINK BRANCH 16 15 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BOX 3O1 ;
        PATH (0.844,0.73)(0.977,0.73) ;
        LABEL '{LWI I 0 255 255 }Manufactured Part' ;
        LABEL COORDINATES (0.864,0.71) ;
        SINK BORDER O2 (0.977,0.73) ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BORDER M2 (0.198,0.968) ;
        PATH (0.198,0.968)(0.198,0.397) ;
        LABEL '{LWI I 0 255 255 }CAD-CAM System' ;
        LABEL COORDINATES (0.156,0.929) ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BORDER M3 (0.658,0.968) ;
        PATH (0.658,0.968)(0.658,0.833) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Tool' ;
        LABEL COORDINATES (0.639,0.929) ;
        SINK BOX 3M2 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BORDER M4 (0.718,0.968) ;
        PATH (0.718,0.968)(0.718,0.833) ;
        LABEL '{LWI I 0 255 255 }Clamping<CR>Tools' ;
        LABEL COORDINATES (0.693,0.938) ;
        SINK BOX 3M3 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BOX 3O2 ;
        PATH (0.844,0.782)(0.871,0.782)(0.871,0.873)(0.085,0.873)(0.085,0.637) ;
        LABEL '{LWI I 0 255 255 }Finished Part Issues' ;
        LABEL COORDINATES (0.273,0.838) ;
        SINK JOIN 13 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BOX 1O2 ;
        PATH (0.293,0.331)(0.346,0.331) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Stages' ;
        LABEL COORDINATES (0.298,0.329) ;
        SINK JOIN 36 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BRANCH 2 ;
        PATH (0.198,0.091)(0.198,0.133) ;
        LABEL 'Final Part Model' ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BRANCH 2 ;
        PATH (0.198,0.091)(0.563,0.091) ;
        LABEL 'Final Part Model' ;
        SINK BRANCH 32 31 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE JOIN 9 14 ;
        PATH (0.085,0.637)(0.085,0.488) ;
        LABEL '{LWI I 0 255 255 }Part Issues' ;
        LABEL COORDINATES (0.059,0.556) ;
        SINK BRANCH 37 35 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BOX 2O1 ;
        PATH (0.586,0.498)(0.616,0.498)(0.616,0.637)(0.085,0.637) ;
        LABEL '{LWI I 0 255 255 }FEM Simulation Issues' ;
        LABEL COORDINATES (0.293,0.62) ;
        SINK JOIN 13 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BRANCH 4 ;
        PATH (0.513,0.168)(0.661,0.168) ;
        LABEL 'SPIF Setup Definition' ;
        SINK BRANCH 34 33 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BRANCH 4 ;
        PATH (0.513,0.168)(0.513,0.433) ;
        LABEL '{LWI I 0 255 255 }SPIF Setup<CR>Definition' ;
        LABEL COORDINATES (0.903,0.165) ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 17 ;
        SOURCE BRANCH 36 ;
        PATH (0.408,0.331)(0.44,0.331) ;
        LABEL '{LWI I 0 255 255 }Technical<CR>Report' ;
        LABEL COORDINATES (0.903,0.329) ;
        SINK JOIN 29 ;
      ENDSEG ;
      ARROWSEG 18 ;
        SOURCE BRANCH 36 ;
        PATH (0.408,0.331)(0.408,0.433) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Stages' ;
        LABEL COORDINATES (0.381,0.383) ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 19 ;
        SOURCE BOX 1O3 ;
        PATH (0.293,0.228)(0.47,0.228) ;
        LABEL 'NC Program' ;
        SINK BRANCH 21 20 ;
      ENDSEG ;
      ARROWSEG 20 ;
        SOURCE BRANCH 19 ;
        PATH (0.47,0.228)(0.746,0.228) ;
        LABEL 'NC Program' ;
        SINK BRANCH 23 22 ;
      ENDSEG ;
      ARROWSEG 21 ;
        SOURCE BRANCH 19 ;
        PATH (0.47,0.228)(0.47,0.433) ;
        LABEL 'NC Program' ;
        SINK BOX 2C3 ;
      ENDSEG ;
      ARROWSEG 22 ;
        SOURCE BRANCH 20 ;
        PATH (0.746,0.228)(0.977,0.228) ;
        LABEL '{LWI I 0 255 255 }NC<CR>Program' ;
        LABEL COORDINATES (0.912,0.229) ;
        SINK BORDER O3 (0.977,0.228) ;
      ENDSEG ;
      ARROWSEG 23 ;
        SOURCE BRANCH 20 ;
        PATH (0.746,0.228)(0.746,0.679) ;
        LABEL 'NC Program' ;
        SINK BOX 3C2 ;
      ENDSEG ;
      ARROWSEG 24 ;
        SOURCE BORDER M5 (0.493,0.968) ;
        PATH (0.493,0.968)(0.493,0.56) ;
        LABEL '{LWI I 0 255 255 }FEA<CR>System' ;
        LABEL COORDINATES (0.478,0.947) ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 25 ;
        SOURCE BORDER M6 (0.78,0.968) ;
        PATH (0.78,0.968)(0.78,0.833) ;
        LABEL '{LWI I 0 255 255 }3D<CR>Scanner<CR>System' ;
        LABEL COORDINATES (0.771,0.938) ;
        SINK BOX 3M4 ;
      ENDSEG ;
      ARROWSEG 26 ;
        SOURCE BORDER M7 (0.837,0.968) ;
        PATH (0.837,0.968)(0.837,0.833) ;
        LABEL '{LWI I 0 255 255 }Measurement<CR>Tools' ;
        LABEL COORDINATES (0.83,0.929) ;
        SINK BOX 3M5 ;
      ENDSEG ;
      ARROWSEG 27 ;
        SOURCE BORDER M8 (0.428,0.968) ;
        PATH (0.428,0.968)(0.428,0.56) ;
        LABEL '{LWI I 0 255 255 }NC Code<CR>Converter' ;
        LABEL COORDINATES (0.41,0.938) ;
        SINK BOX 2M2 ;
      ENDSEG ;
      ARROWSEG 28 ;
        SOURCE TUNNEL  {LWI Q}BORDER ;
        PATH (0.149,0.031)(0.149,0.133) ;
        LABEL '{LWI I 0 255 255 }SPIF<CR>Knowledge' ;
        LABEL COORDINATES (0.078,0.083) ;
        SINK BOX 1C2 ;
      ENDSEG ;
      ARROWSEG 29 ;
        SOURCE JOIN 17 30 ;
        PATH (0.44,0.331)(0.977,0.331) ;
        LABEL 'Technical Report' ;
        SINK BORDER O4 (0.977,0.331) ;
      ENDSEG ;
      ARROWSEG 30 ;
        SOURCE BOX 1O4 ;
        PATH (0.293,0.271)(0.44,0.271)(0.44,0.331) ;
        LABEL '{LWI I 0 255 255 }Intermediate<CR>Part Models' ;
        LABEL COORDINATES (0.298,0.274) ;
        SINK JOIN 29 ;
      ENDSEG ;
      ARROWSEG 31 ;
        SOURCE BRANCH 12 ;
        PATH (0.563,0.091)(0.7,0.091)(0.7,0.679) ;
        LABEL '{LWI I 0 255 255 }Final Part<CR>Model' ;
        LABEL COORDINATES (0.2,0.056) ;
        SINK BOX 3C3 ;
      ENDSEG ;
      ARROWSEG 32 ;
        SOURCE BRANCH 12 ;
        PATH (0.563,0.091)(0.563,0.433) ;
        LABEL '{LWI I 0 255 255 }Raw<CR>Material' ;
        LABEL COORDINATES (0.547,0.129) ;
        SINK BOX 2C4 ;
      ENDSEG ;
      ARROWSEG 33 ;
        SOURCE BRANCH 15 ;
        PATH (0.661,0.168)(0.977,0.168) ;
        LABEL 'SPIF Setup Definition' ;
        SINK BORDER O1 (0.977,0.168) ;
      ENDSEG ;
      ARROWSEG 34 ;
        SOURCE BRANCH 15 ;
        PATH (0.661,0.168)(0.661,0.679) ;
        LABEL '{LWI I 0 255 255 }Blank<CR>Definition' ;
        LABEL COORDINATES (0.639,0.447) ;
        SINK BOX 3C4 ;
      ENDSEG ;
      ARROWSEG 35 ;
        SOURCE BRANCH 13 ;
        PATH (0.085,0.488)(0.085,0.265)(0.103,0.265) ;
        LABEL 'Part Issues' ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 36 ;
        SOURCE JOIN 37 10 ;
        PATH (0.346,0.331)(0.408,0.331) ;
        LABEL 'Technical Report' ;
        SINK BRANCH 18 17 ;
      ENDSEG ;
      ARROWSEG 37 ;
        SOURCE BRANCH 13 ;
        PATH (0.085,0.488)(0.346,0.488)(0.346,0.331) ;
        LABEL 'Part Issues' ;
        SINK JOIN 36 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A1 ;
      CREATION DATE 22/2/2018 ;
      REVISION DATE 22/2/2018 ;
      TITLE 'Define NC Program' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Define Blank and Tools' ;
        BOX COORDINATES (0.108,0.315) (0.23,0.179) ;
        DETAIL REFERENCE N A11 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Define Forming Tool' ;
        BOX COORDINATES (0.19,0.488) (0.381,0.37) ;
        DETAIL REFERENCE N A12 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Define Forming Strategies' ;
        BOX COORDINATES (0.376,0.67) (0.615,0.515) ;
        DETAIL REFERENCE N A13 ;
      ENDBOX ;
      BOX 4 ;
        NAME '{LWI I 4 255 255 255}Simulate and Generate NC' ;
        BOX COORDINATES (0.61,0.833) (0.844,0.715) ;
        DETAIL REFERENCE N A14 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER C1 (0.155,0.031) ;
        PATH (0.155,0.031)(0.155,0.144) ;
        LABEL '{LWI I 0 255 255 }Final Part<CR>Model' ;
        LABEL COORDINATES (0.2,0.074) ;
        SINK BRANCH 5 4 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 2O1 ;
        PATH (0.381,0.429)(0.51,0.429) ;
        LABEL '{LWI I 0 255 255 }Forming Tool<CR>Definition' ;
        LABEL COORDINATES (0.43,0.429) ;
        SINK JOIN 15 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BORDER I1 (0.019,0.409) ;
        PATH (0.019,0.409)(0.084,0.409) ;
        LABEL '{LWI I 0 255 255 }Part Issues' ;
        LABEL COORDINATES (0.02,0.392) ;
        SINK BRANCH 13 23 12 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BRANCH 1 ;
        PATH (0.155,0.144)(0.155,0.179) ;
        LABEL 'Final Part Model' ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BRANCH 1 ;
        PATH (0.155,0.144)(0.263,0.144) ;
        LABEL 'Final Part Model' ;
        SINK BRANCH 7 6 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BRANCH 5 ;
        PATH (0.263,0.144)(0.263,0.37) ;
        LABEL 'Final Part Model' ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BRANCH 5 ;
        PATH (0.263,0.144)(0.409,0.144)(0.409,0.515) ;
        LABEL 'Final Part Model' ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BOX 4O1 ;
        PATH (0.844,0.804)(0.882,0.804)(0.882,0.897)(0.335,0.897) ;
        LABEL 'NC Program Issues' ;
        SINK BRANCH 10 9 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BRANCH 8 ;
        PATH (0.335,0.897)(0.14,0.897)(0.14,0.448)(0.19,0.448) ;
        LABEL 'NC Program Issues' ;
        SINK BOX 2I1 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BRANCH 8 ;
        PATH (0.335,0.897)(0.335,0.618)(0.376,0.618) ;
        LABEL '{LWI I 0 255 255 }NC Program Issues' ;
        LABEL COORDINATES (0.41,0.883) ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BOX 3O1 ;
        PATH (0.615,0.655)(0.688,0.655)(0.688,0.715) ;
        LABEL '{LWI I 0 255 255 }SPIF CNC Model' ;
        LABEL COORDINATES (0.63,0.638) ;
        SINK BOX 4C1 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BRANCH 3 ;
        PATH (0.084,0.409)(0.19,0.409) ;
        LABEL 'Part Issues' ;
        SINK BOX 2I2 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BRANCH 3 ;
        PATH (0.084,0.409)(0.084,0.247)(0.108,0.247) ;
        LABEL 'Part Issues' ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BOX 1O1 ;
        PATH (0.23,0.285)(0.51,0.285)(0.51,0.429) ;
        LABEL '{LWI I 0 255 255 }Tools<CR>Definition' ;
        LABEL COORDINATES (0.434,0.283) ;
        SINK JOIN 15 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE JOIN 14 2 ;
        PATH (0.51,0.429)(0.528,0.429) ;
        LABEL 'SPIF Setup Definition' ;
        SINK JOIN 18 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BRANCH 18 ;
        PATH (0.55,0.429)(0.766,0.429) ;
        LABEL 'SPIF Setup Definition' ;
        SINK BRANCH 20 21 ;
      ENDSEG ;
      ARROWSEG 17 ;
        SOURCE BRANCH 18 ;
        PATH (0.55,0.429)(0.55,0.515) ;
        LABEL '{LWI I 0 255 255 }SPIF Setup Definition' ;
        LABEL COORDINATES (0.839,0.41) ;
        SINK BOX 3C2 ;
      ENDSEG ;
      ARROWSEG 18 ;
        SOURCE JOIN 19 15 ;
        PATH (0.528,0.429)(0.55,0.429) ;
        LABEL 'SPIF Setup Definition' ;
        SINK BRANCH 17 16 ;
      ENDSEG ;
      ARROWSEG 19 ;
        SOURCE BOX 1O2 ;
        PATH (0.23,0.224)(0.528,0.224)(0.528,0.429) ;
        LABEL '{LWI I 0 255 255 }Blank Definition' ;
        LABEL COORDINATES (0.43,0.21) ;
        SINK JOIN 18 ;
      ENDSEG ;
      ARROWSEG 20 ;
        SOURCE BRANCH 16 ;
        PATH (0.766,0.429)(0.977,0.429) ;
        LABEL 'SPIF Setup Definition' ;
        SINK BORDER O1 (0.977,0.429) ;
      ENDSEG ;
      ARROWSEG 21 ;
        SOURCE BRANCH 16 ;
        PATH (0.766,0.429)(0.766,0.715) ;
        LABEL 'SPIF Setup Definition' ;
        SINK BOX 4C2 ;
      ENDSEG ;
      ARROWSEG 22 ;
        SOURCE BOX 4O2 ;
        PATH (0.844,0.745)(0.977,0.745) ;
        LABEL '{LWI I 0 255 255 }NC Program' ;
        LABEL COORDINATES (0.883,0.729) ;
        SINK BORDER O3 (0.977,0.745) ;
      ENDSEG ;
      ARROWSEG 23 ;
        SOURCE BRANCH 3 ;
        PATH (0.084,0.409)(0.084,0.564)(0.376,0.564) ;
        LABEL 'Part Issues' ;
        SINK BOX 3I2 ;
      ENDSEG ;
      ARROWSEG 24 ;
        SOURCE BORDER C2 (0.587,0.031) ;
        PATH (0.587,0.031)(0.587,0.118) ;
        LABEL '{LWI I 0 255 255 }SPIF<CR>strategy' ;
        LABEL COORDINATES (0.566,0.274) ;
        SINK BRANCH 28 29 ;
      ENDSEG ;
      ARROWSEG 25 ;
        SOURCE BOX 3O2 ;
        PATH (0.615,0.548)(0.853,0.548) ;
        LABEL '{LWI I 0 255 255 }Forming Stages' ;
        LABEL COORDINATES (0.639,0.538) ;
        SINK JOIN 26 ;
      ENDSEG ;
      ARROWSEG 26 ;
        SOURCE JOIN 25 27 ;
        PATH (0.853,0.548)(0.977,0.548) ;
        LABEL '{LWI I 0 255 255 }Technical<CR>Report' ;
        LABEL COORDINATES (0.908,0.547) ;
        SINK BORDER O4 (0.977,0.548) ;
      ENDSEG ;
      ARROWSEG 27 ;
        SOURCE BOX 3O3 ;
        PATH (0.615,0.593)(0.853,0.593)(0.853,0.548) ;
        LABEL '{LWI I 0 255 255 }Intermediate<CR>Part Models' ;
        LABEL COORDINATES (0.644,0.592) ;
        SINK JOIN 26 ;
      ENDSEG ;
      ARROWSEG 28 ;
        SOURCE BRANCH 24 ;
        PATH (0.587,0.118)(0.587,0.515) ;
        LABEL '{LWI I 0 255 255 }SPIF<CR>Knowledge' ;
        LABEL COORDINATES (0.561,0.065) ;
        SINK BOX 3C3 ;
      ENDSEG ;
      ARROWSEG 29 ;
        SOURCE BRANCH 24 ;
        PATH (0.587,0.118)(0.344,0.118) ;
        LABEL 'SPIF Knowledge' ;
        SINK BRANCH 30 31 ;
      ENDSEG ;
      ARROWSEG 30 ;
        SOURCE BRANCH 29 ;
        PATH (0.344,0.118)(0.219,0.118)(0.219,0.179) ;
        LABEL 'SPIF Knowledge' ;
        SINK BOX 1C2 ;
      ENDSEG ;
      ARROWSEG 31 ;
        SOURCE BRANCH 29 ;
        PATH (0.344,0.118)(0.344,0.37) ;
        LABEL 'SPIF Knowledge' ;
        SINK BOX 2C2 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A13 ;
      CREATION DATE 22/2/2018 ;
      REVISION DATE 22/2/2018 ;
      TITLE 'Define Forming Strategies' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Define Forming Stages' ;
        BOX COORDINATES (0.176,0.388) (0.4,0.27) ;
        DETAIL REFERENCE N A131 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Design Intermediate Parts' ;
        BOX COORDINATES (0.366,0.624) (0.659,0.506) ;
        DETAIL REFERENCE N A132 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Define Tool Trajectories' ;
        BOX COORDINATES (0.683,0.897) (0.869,0.76) ;
        DETAIL REFERENCE N A133 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BOX 3O1 ;
        PATH (0.869,0.829)(0.977,0.829) ;
        LABEL '{LWI I 0 255 255 }SPIF CNC Model' ;
        LABEL COORDINATES (0.878,0.801) ;
        SINK BORDER O1 (0.977,0.829) ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER I1 (0.019,0.88) ;
        PATH (0.019,0.88)(0.683,0.88) ;
        LABEL '{LWI I 0 255 255 }NC Program<CR>Issues' ;
        LABEL COORDINATES (0.039,0.847) ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BORDER C1 (0.6,0.031) ;
        PATH (0.6,0.031)(0.6,0.204) ;
        LABEL '{LWI I 0 255 255 }Final Part<CR>Model' ;
        LABEL COORDINATES (0.576,0.138) ;
        SINK BRANCH 10 9 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE TUNNEL  {LWI Q}BORDER ;
        PATH (0.833,0.031)(0.833,0.76) ;
        LABEL '{LWI I 0 255 255 }Tools Definition' ;
        LABEL COORDINATES (0.82,0.092) ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BOX 1O1 ;
        PATH (0.4,0.329)(0.425,0.329) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Stages' ;
        LABEL COORDINATES (0.4,0.41) ;
        SINK BRANCH 23 21 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BOX 2O1 ;
        PATH (0.659,0.565)(0.74,0.565) ;
        LABEL '{LWI I 0 255 255 }Intermediate<CR>Part Models' ;
        LABEL COORDINATES (0.664,0.565) ;
        SINK BRANCH 24 26 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BRANCH 9 ;
        PATH (0.6,0.202)(0.6,0.506) ;
        LABEL 'Final Part Model' ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BRANCH 9 ;
        PATH (0.6,0.202)(0.786,0.202)(0.786,0.76) ;
        LABEL 'Final Part Model' ;
        SINK BOX 3C2 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BRANCH 3 ;
        PATH (0.6,0.204)(0.6,0.442) ;
        LABEL 'Final Part Model' ;
        SINK BRANCH 7 8 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BRANCH 3 ;
        PATH (0.6,0.204)(0.344,0.204)(0.344,0.27) ;
        LABEL 'Final Part Model' ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE TUNNEL  {LWI Q}BORDER ;
        PATH (0.256,0.031)(0.256,0.094) ;
        LABEL '{LWI I 0 255 255 }Forming Tool Definition' ;
        LABEL COORDINATES (0.264,0.065) ;
        SINK BRANCH 12 13 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BRANCH 11 ;
        PATH (0.256,0.094)(0.256,0.27) ;
        LABEL 'Forming Tool Definition' ;
        SINK BOX 1C2 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BRANCH 11 ;
        PATH (0.256,0.094)(0.483,0.094)(0.483,0.506) ;
        LABEL 'Forming Tool Definition' ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE TUNNEL  {LWI Q}BORDER ;
        PATH (0.542,0.031)(0.542,0.153) ;
        LABEL '{LWI I 0 255 255 }Blank Definition' ;
        LABEL COORDINATES (0.503,0.092) ;
        SINK BRANCH 16 15 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BRANCH 14 ;
        PATH (0.542,0.153)(0.542,0.506) ;
        LABEL 'Blank Definition' ;
        SINK BOX 2C3 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BRANCH 14 ;
        PATH (0.542,0.153)(0.288,0.153)(0.288,0.27) ;
        LABEL 'Blank Definition' ;
        SINK BOX 1C3 ;
      ENDSEG ;
      ARROWSEG 17 ;
        SOURCE BORDER I2 (0.019,0.565) ;
        PATH (0.019,0.565)(0.113,0.565) ;
        LABEL '{LWI I 0 255 255 }Part Issues' ;
        LABEL COORDINATES (0.02,0.547) ;
        SINK BRANCH 19 18 20 ;
      ENDSEG ;
      ARROWSEG 18 ;
        SOURCE BRANCH 17 ;
        PATH (0.113,0.565)(0.366,0.565) ;
        LABEL 'Part Issues' ;
        SINK BOX 2I1 ;
      ENDSEG ;
      ARROWSEG 19 ;
        SOURCE BRANCH 17 ;
        PATH (0.113,0.565)(0.113,0.329)(0.176,0.329) ;
        LABEL 'Part Issues' ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 20 ;
        SOURCE BRANCH 17 ;
        PATH (0.113,0.565)(0.113,0.796)(0.683,0.796) ;
        LABEL 'Part Issues' ;
        SINK BOX 3I2 ;
      ENDSEG ;
      ARROWSEG 21 ;
        SOURCE BRANCH 5 ;
        PATH (0.425,0.329)(0.741,0.329) ;
        LABEL '{LWI I 0 255 255 }Technical<CR>Report' ;
        LABEL COORDINATES (0.898,0.329) ;
        SINK JOIN 25 ;
      ENDSEG ;
      ARROWSEG 22 ;
        SOURCE BORDER C3 (0.207,0.031) ;
        PATH (0.207,0.031)(0.207,0.27) ;
        LABEL '{LWI I 0 255 255 }SPIF<CR>Knowledge' ;
        LABEL COORDINATES (0.181,0.092) ;
        SINK BOX 1C4 ;
      ENDSEG ;
      ARROWSEG 23 ;
        SOURCE BRANCH 5 ;
        PATH (0.425,0.329)(0.425,0.506) ;
        LABEL 'Forming Stages' ;
        SINK BOX 2C4 ;
      ENDSEG ;
      ARROWSEG 24 ;
        SOURCE BRANCH 6 ;
        PATH (0.74,0.565)(0.74,0.76) ;
        LABEL 'Intermediate Part Models' ;
        SINK BOX 3C3 ;
      ENDSEG ;
      ARROWSEG 25 ;
        SOURCE JOIN 26 21 ;
        PATH (0.741,0.329)(0.977,0.329) ;
        LABEL 'Technical Report' ;
        SINK BORDER O3 (0.977,0.329) ;
      ENDSEG ;
      ARROWSEG 26 ;
        SOURCE BRANCH 6 ;
        PATH (0.74,0.565)(0.741,0.565)(0.741,0.329) ;
        LABEL 'Intermediate Part Models' ;
        SINK JOIN 25 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A2 ;
      CREATION DATE 22/2/2018 ;
      REVISION DATE 22/2/2018 ;
      TITLE 'Finite Element Analysis' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Extract Tool Trajectory' ;
        BOX COORDINATES (0.122,0.242) (0.322,0.124) ;
        DETAIL REFERENCE N A21 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Define FEM' ;
        BOX COORDINATES (0.327,0.56) (0.664,0.433) ;
        DETAIL REFERENCE N A22 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Run and Analyze FEM' ;
        BOX COORDINATES (0.717,0.806) (0.898,0.688) ;
        DETAIL REFERENCE N A23 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BOX 3O1 ;
        PATH (0.898,0.747)(0.977,0.747) ;
        LABEL '{LWI I 0 255 255 }FEM<CR>Simulation<CR>Issues' ;
        LABEL COORDINATES (0.908,0.72) ;
        SINK BORDER O1 (0.977,0.747) ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 1O1 ;
        PATH (0.322,0.183)(0.35,0.183)(0.35,0.433) ;
        LABEL '{LWI I 0 255 255 }Tool<CR>Trajectory' ;
        LABEL COORDINATES (0.327,0.329) ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BORDER C2 (0.602,0.031) ;
        PATH (0.602,0.031)(0.602,0.433) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Stages' ;
        LABEL COORDINATES (0.581,0.092) ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BOX 2O1 ;
        PATH (0.664,0.497)(0.81,0.497)(0.81,0.688) ;
        LABEL '{LWI I 0 255 255 }SPIF Numerical<CR>Model' ;
        LABEL COORDINATES (0.693,0.501) ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BORDER M1 (0.491,0.968) ;
        PATH (0.491,0.968)(0.491,0.872) ;
        LABEL '{LWI I 0 255 255 }FEA<CR>System' ;
        LABEL COORDINATES (0.551,0.929) ;
        SINK BRANCH 11 10 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BORDER C1 (0.511,0.031) ;
        PATH (0.511,0.031)(0.511,0.433) ;
        LABEL '{LWI I 0 255 255 }SPIF Setup<CR>Definition' ;
        LABEL COORDINATES (0.483,0.12) ;
        SINK BOX 2C3 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BORDER C3 (0.227,0.031) ;
        PATH (0.227,0.031)(0.227,0.124) ;
        LABEL '{LWI I 0 255 255 }NC<CR>Program' ;
        LABEL COORDINATES (0.225,0.083) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BORDER C4 (0.43,0.031) ;
        PATH (0.43,0.031)(0.43,0.433) ;
        LABEL '{LWI I 0 255 255 }Raw<CR>Material' ;
        LABEL COORDINATES (0.415,0.12) ;
        SINK BOX 2C4 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BORDER M2 (0.227,0.968) ;
        PATH (0.227,0.968)(0.227,0.242) ;
        LABEL '{LWI I 0 255 255 }NC Code<CR>Converter' ;
        LABEL COORDINATES (0.21,0.892) ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BRANCH 5 ;
        PATH (0.491,0.872)(0.491,0.56) ;
        LABEL 'FEA System' ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BRANCH 5 ;
        PATH (0.491,0.872)(0.809,0.872)(0.809,0.806) ;
        LABEL 'FEA System' ;
        SINK BOX 3M1 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A3 ;
      CREATION DATE 22/2/2018 ;
      REVISION DATE 22/2/2018 ;
      TITLE 'Manufacture and Inspect Part' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 5 255 255 255}Manufacturing' ;
        BOX COORDINATES (0.112,0.424) (0.337,0.197) ;
        DETAIL REFERENCE N A31 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 5 255 255 255}Manual Inspection' ;
        BOX COORDINATES (0.41,0.597) (0.595,0.397) ;
        DETAIL REFERENCE N A32 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 5 255 255 255}Inspection by DIP' ;
        BOX COORDINATES (0.664,0.824) (0.839,0.615) ;
        DETAIL REFERENCE N A33 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER C3 (0.483,0.031) ;
        PATH (0.483,0.031)(0.483,0.247) ;
        LABEL '{LWI I 0 255 255 }Final Part<CR>Model' ;
        LABEL COORDINATES (0.454,0.056) ;
        SINK BRANCH 10 11 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 1O1 ;
        PATH (0.337,0.301)(0.436,0.301) ;
        LABEL '{LWI I 0 255 255 }Manufactured<CR>Part' ;
        LABEL COORDINATES (0.898,0.301) ;
        SINK BRANCH 17 16 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BOX 2O1 ;
        PATH (0.595,0.534)(0.859,0.534) ;
        LABEL '{LWI I 0 255 255 }Part<CR>Issues' ;
        LABEL COORDINATES (0.932,0.538) ;
        SINK JOIN 8 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BORDER M3 (0.281,0.968) ;
        PATH (0.281,0.968)(0.281,0.424) ;
        LABEL '{LWI I 0 255 255 }Clamping<CR>Tools' ;
        LABEL COORDINATES (0.264,0.947) ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BORDER M2 (0.225,0.968) ;
        PATH (0.225,0.968)(0.225,0.424) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Tool' ;
        LABEL COORDINATES (0.2,0.901) ;
        SINK BOX 1M2 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BORDER M1 (0.169,0.968) ;
        PATH (0.169,0.968)(0.169,0.424) ;
        LABEL '{LWI I 0 255 255 }NC Machine' ;
        LABEL COORDINATES (0.122,0.947) ;
        SINK BOX 1M3 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE TUNNEL  {LWI Q}BORDER ;
        PATH (0.556,0.031)(0.556,0.397) ;
        LABEL '{LWI I 0 255 255 }Quality and Inspection<CR>Rules' ;
        LABEL COORDINATES (0.512,0.129) ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE JOIN 3 9 ;
        PATH (0.859,0.534)(0.977,0.534) ;
        LABEL 'Part Issues' ;
        SINK BORDER O2 (0.977,0.534) ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BOX 3O1 ;
        PATH (0.839,0.685)(0.859,0.685)(0.859,0.534) ;
        LABEL 'Part Issues' ;
        SINK JOIN 8 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BRANCH 1 ;
        PATH (0.483,0.247)(0.483,0.397) ;
        LABEL 'Final Part Model' ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BRANCH 1 ;
        PATH (0.483,0.247)(0.722,0.247)(0.722,0.615) ;
        LABEL 'Final Part Model' ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BORDER C2 (0.187,0.031) ;
        PATH (0.187,0.031)(0.187,0.197) ;
        LABEL '{LWI I 0 255 255 }NC Program' ;
        LABEL COORDINATES (0.151,0.083) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BORDER M5 (0.496,0.968) ;
        PATH (0.496,0.968)(0.496,0.597) ;
        LABEL '{LWI I 0 255 255 }Measurement<CR>Tools' ;
        LABEL COORDINATES (0.473,0.938) ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BORDER M4 (0.747,0.968) ;
        PATH (0.747,0.968)(0.747,0.824) ;
        LABEL '{LWI I 0 255 255 }3D<CR>Scanner<CR>System' ;
        LABEL COORDINATES (0.727,0.929) ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BORDER C4 (0.268,0.031) ;
        PATH (0.268,0.031)(0.268,0.197) ;
        LABEL '{LWI I 0 255 255 }Blank<CR>Definition' ;
        LABEL COORDINATES (0.249,0.101) ;
        SINK BOX 1C2 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BRANCH 2 ;
        PATH (0.436,0.301)(0.783,0.301) ;
        LABEL 'Manufactured Part' ;
        SINK BRANCH 22 21 ;
      ENDSEG ;
      ARROWSEG 17 ;
        SOURCE BRANCH 2 ;
        PATH (0.436,0.301)(0.436,0.397) ;
        LABEL '{LWI I 0 255 255 }Manufactured<CR>Part' ;
        LABEL COORDINATES (0.4,0.347) ;
        SINK BOX 2C3 ;
      ENDSEG ;
      ARROWSEG 18 ;
        SOURCE BOX 2O2 ;
        PATH (0.595,0.458)(0.888,0.458) ;
        LABEL '{LWI I 0 255 255 }Manually<CR>Inspected<CR>Part' ;
        LABEL COORDINATES (0.634,0.456) ;
        SINK JOIN 23 ;
      ENDSEG ;
      ARROWSEG 19 ;
        SOURCE JOIN 21 23 ;
        PATH (0.888,0.301)(0.977,0.301) ;
        LABEL 'Manufactured Part' ;
        SINK BORDER O1 (0.977,0.301) ;
      ENDSEG ;
      ARROWSEG 20 ;
        SOURCE BOX 3O2 ;
        PATH (0.839,0.764)(0.888,0.764)(0.888,0.458) ;
        LABEL '{LWI I 0 255 255 }Digitally<CR>Inspected<CR>Part' ;
        LABEL COORDINATES (0.869,0.656) ;
        SINK JOIN 23 ;
      ENDSEG ;
      ARROWSEG 21 ;
        SOURCE BRANCH 16 ;
        PATH (0.783,0.301)(0.888,0.301) ;
        LABEL 'Manufactured Part' ;
        SINK JOIN 19 ;
      ENDSEG ;
      ARROWSEG 22 ;
        SOURCE BRANCH 16 ;
        PATH (0.783,0.301)(0.783,0.615) ;
        LABEL '{LWI I 0 255 255 }Manufactured<CR>Part' ;
        LABEL COORDINATES (0.751,0.356) ;
        SINK BOX 3C2 ;
      ENDSEG ;
      ARROWSEG 23 ;
        SOURCE JOIN 20 18 ;
        PATH (0.888,0.458)(0.888,0.301) ;
        LABEL '{LWI I 0 255 255 }Inspected<CR>Part' ;
        LABEL COORDINATES (0.869,0.383) ;
        SINK JOIN 19 ;
      ENDSEG ;
    ENDDIAGRAM ;
  ENDMODEL ;
ENDKIT ;
